name: Build and Push Docker Image

on:
  push:
    branches: [main]  # main branch ki push chesinappudu run avtundi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t vprathima/my-app:latest .

      - name: Push Docker image
        run: docker push vprathima/my-app:latest
